export const first_names =
    [
        {name: "Şiyar", meaning: "Watchful person, vigilant", gender: "male"},
        {name: "Cemal", meaning: "Beauty, this name has an Arabic origin", gender: "male"},
        {name: "Hogir", meaning: "Pal", gender: "male"},
        {name: "Rênas", meaning: "The one who knows the road very well", gender: "male"},
        {name: "Roj", meaning: "Sun, day in some dialects", gender: "both"},
        {name: "Dêrsim", meaning: "A Kurdish city in Bakur or Northern Kurdistan", gender: "male"},
        {name: "Munzur", meaning: "A river name in Bakur or Northern Kurdistan", gender: "male"},
        {name: "Botan", meaning: "A historical region name in Bakur or Northern Kurdistan", gender: "male"},
        {name: "Mezlum", meaning: "Oppressed", gender: "male"},
        {name: "Serhed", meaning: "The area to the north of the border, Hed means the border that divided Rojava and Bakur so Serhed means Bakur", gender: "male"},
        {name: "Serbest", meaning: "Free", gender: "male"},
        {name: "Tekoşer", meaning: "Struggler", gender: "male"},
        {name: "Agirî", meaning: "A mountain name in Bakur or Northern Kurdistan", gender: "male"},
        {name: "Agir", meaning: "Fire", gender: "male"},
        {name: "Dijwar", meaning: "Strong, like saying this chemical material is so strong", gender: "male"},
        {name: "Gelî", meaning: "Waterfall", gender: "male"},
        {name: "Şerzan", meaning: "Knows how to fight very well", gender: "male"},
        {name: "Xebat", meaning: "Work, the good meaning of it", gender: "male"},
        {name: "Serdem", meaning: "Due date, he knows well about the age we live in", gender: "male"},
        {name: "Rûken", meaning: "The one with smiley face", gender: "female"},
        {name: "Bêrîvan", meaning: "The woman who milks the cattle", gender: "female"},
        {name: "Xemgîn", meaning: "Sad", gender: "male"},
        {name: "Destan", meaning: "Epic", gender: "female"},
            {name: "Ciwan", meaning: "Young, beautiful", gender: "male"},
            {name: "Amed", meaning: "A Kurdish city in Bakur or Northern Kurdistan, also the capital of the big Kurdistan", gender: "male"},
            {name: "Şervan", meaning: "Fighter", gender: "male"},
            {name: "Çîçek", meaning: "Rose", gender: "female"},
            {name: "Êrîş", meaning: "Attack", gender: "male"},
            {name: "Cesur", meaning: "Bold", gender: "male"},
            {name: "Kerwan", meaning: "Convoy", gender: "male"},
            {name: "Ferhad", meaning: "True lover", gender: "male"},
            {name: "Diyar", meaning: "Country, it has an islamic origin and multiple meanings in Arabic and Urdu", gender: "male"},
            {name: "Çiya", meaning: "Mountain", gender: "male"},
            {name: "Serdar", meaning: "The one in the top, when it literally means the one on the tree", gender: "male"},
            {name: "Şevreş", meaning: "Dark night", gender: "both"},
            {name: "Hozan", meaning: "Singer", gender: "male"},
            {name: "Rojda", meaning: "Day-giver, Sun-giver", gender: "female"},
            {name: "Rojîn", meaning: "The lively face", gender: "female"},
            {name: "Ronî", meaning: "Light", gender: "male"},
            {name: "Şîmal", meaning: "A Kind of tree, also there is a village in Azerbaijan with this name", gender: "female"},
            {name: "Newroz", meaning: "The new day, and it is also the name of the national Kurdish day, the same day that different Iranian people celebrate it", gender: "female"},
            {name: "Lewend", meaning: "Graceful", gender: "male"},
            {name: "Xelîl", meaning: "Lover, it means the same in Arabic as well", gender: "male"},
            {name: "Welat", meaning: "Homeland", gender: "male"},
            {name: "Elîf", meaning: "A, The first letter in different alphabets", gender: "female"},
            {name: "Herekol", meaning: "A mountain name in Bakur or Northern Kurdistan", gender: "male"},
            {name: "Canşêr", meaning: "The tiger soul", gender: "male"},
            {name: "Jînda", meaning: "The one who gave the life", gender: "female"},
            {name: "Rêber", meaning: "The leader", gender: "male"},
            {name: "Siyabend", meaning: "Slender as a thread shadow, it is a the male hero name in the traditional Kurdish love story (Siyabend û Xecê)", gender: "male"},
            {name: "Partîzan", meaning: "Resistant", gender: "male"},
            {name: "Şoreş", meaning: "Revolution", gender: "male"},
            {name: "Argeş", meaning: "Blazing fire", gender: "male"},
            {name: "Bahoz", meaning: "Storm", gender: "male"},
            {name: "Berxwedan", meaning: "Resistance", gender: "male"},
            {name: "Egîd", meaning: "Brave, historically the bravest man in the village/neighbourhood was named Egîd", gender: "male"},
            {name: "Sîpan", meaning: "A mountain name in Bakur or Northern Kurdistan", gender: "male"},
            {name: "Herdem", meaning: "Everytime, the one who is here every time", gender: "male"},
            {name: "Rodî", meaning: "Literally it means the face that saw the sun, or brightness", gender: "male"},
            {name: "Rûbar", meaning: "Opposite or river", gender: "male"},
            {name: "Şivan", meaning: "Shepherd", gender: "male"},
            {name: "Cigerxwîn", meaning: "The bloody liver, the name of a famous Kurdish national poet", gender: "male"},
            {name: "Dilêr", meaning: "Hero, the one that is brave in wars or dangerous situations", gender: "male"},
            {name: "Dilxwaz", meaning: "He has willing, or literally his heart wants to", gender: "male"},
            {name: "Koçer", meaning: "Kurdish Bedouin, the usual nickname of Kurds in the bedouin tribes (mostly historically)", gender: "male"},
            {name: "Tolhildan", meaning: "Revenge", gender: "male"},
            {name: "Karker", meaning: "Worker", gender: "male"},
            {name: "Rûşîn", meaning: "The sad face, solace face", gender: "female"},
            {name: "Arî", meaning: "Aryan", gender: "male"},
            {name: "Zagros", meaning: "A long mountain range name in Rojhilat or Eastern Kurdistan", gender: "male"},
            {name: "Armanc", meaning: "Purpose, Aim", gender: "male"},
            {name: "Berfîn", meaning: "Snow", gender: "female"},
            {name: "Erdal", meaning: "A young person, has the same meaning in Turkish", gender: "male"},
            {name: "Rizgar", meaning: "Liberal", gender: "male"},
            {name: "Rojbîn", meaning: "The one who will bring the sun/day", gender: "female"},
            {name: "Bawer", meaning: "Convinced", gender: "male"},
            {name: "Sefqan", meaning: "The bloody head", gender: "male"},
            {name: "Brusk", meaning: "Hailstones", gender: "male"},
            {name: "Elend", meaning: "The first ray of the sun in the morning", gender: "male"},
            {name: "Zerdeşt", meaning: "Zoroaster", gender: "male"},
            {name: "Dilşad", meaning: "Happy heart", gender: "male"},
            {name: "Lezgîn", meaning: "Hasty", gender: "male"},
            {name: "Nuda", meaning: "New gift, the god has given her again", gender: "female"},
            {name: "Bêrîtan", meaning: "A Kurdish tribe name", gender: "female"},
            {name: "Sînan", meaning: "Spearhead", gender: "male"},
            {name: "Tekoşîn", meaning: "Struggle", gender: "female"},
            {name: "Xwînda", meaning: "Blood giver", gender: "female"},
            {name: "Qendîl", meaning: "A mountain name in Başur or Southern Kurdistan", gender: "male"},
            {name: "Çiyager", meaning: "The one who walk through mountains", gender: "male"},
            {name: "Amara", meaning: "Eternal beauty", gender: "female"},
            {name: "Devrim", meaning: "Revolution, and has the same meaning in Turkish", gender: "male"},
            {name: "Kendal", meaning: "Slope", gender: "male"},
            {name: "Rûstem", meaning: "The name of the Iranian mythic hero Rostam", gender: "male"},
            {name: "Viyan", meaning: "Intention or wish", gender: "female"},
            {name: "Yaşar", meaning: "Ease", gender: "male"},
            {name: "Piling", meaning: "Panther", gender: "male"},
            {name: "Şevger", meaning: "The one who walks in the night", gender: "male"},
            {name: "Çeleng", meaning: "Elegant, gracious, pretty", gender: "male"},
            {name: "Fedekar", meaning: "Sacrificing person", gender: "male"},
            {name: "Azad", meaning: "Free", gender: "male"},
            {name: "Can", meaning: "Soul, young, pretty", gender: "male"},
            {name: "Arîn", meaning: "The continues ache", gender: "female"},
            {name: "Gabar", meaning: "A mountain name in Bakur or Northern Kurdistan", gender: "male"},
            {name: "Canpolat", meaning: "The steely soul", gender: "male"},
            {name: "Çarçela", meaning: "A mountain name in Bakur or Northern Kurdistan", gender: "female"},
            {name: "Çekdar", meaning: "Armed", gender: "male"},
            {name: "Delîla", meaning: "Guide", gender: "female"},
            {name: "Dilşêr", meaning: "The tiger heart", gender: "male"},
            {name: "Hawar", meaning: "Cry for help", gender: "male"},
            {name: "Hewlêr", meaning: "A Kurdish city in Başur or Southern Kurdistan, Erbil", gender: "female"},
            {name: "Qehreman", meaning: "Hero", gender: "male"},
            {name: "Firat", meaning: "Euphrates river", gender: "male"},
            {name: "Tîmaf", meaning: "Thirst for his rights", gender: "male"},
            {name: "Xemlîn", meaning: "adornment", gender: "female"},
            {name: "Warşîn", meaning: "The green homeland", gender: "female"},
            {name: "Jiyan", meaning: "Life", gender: "female"},
            {name: "Vejîn", meaning: "Revival", gender: "female"},
            {name: "Sorxwîn", meaning: "Red blood", gender: "female"},
            {name: "Şîlan", meaning: "Wild rose", gender: "female"},
            {name: "Ronahî", meaning: "Light", gender: "female"},
            {name: "Peyman", meaning: "Agreement", gender: "female"},
            {name: "Raperîn", meaning: "Uprising", gender: "female"},
            {name: "Nejbîr", meaning: "Diligent", gender: "female"},
            {name: "Jiyanda", meaning: "The one who gave the life", gender: "female"},
            {name: "Hêlîn", meaning: "The nest", gender: "female"},
            {name: "Hêvîdar", meaning: "The wisher", gender: "female"},
            {name: "Gulnaz", meaning: "Tender rose", gender: "female"},
            {name: "Gulîstan", meaning: "A house of flowers", gender: "female"},
            {name: "Dîdar", meaning: "Jovial, cheery", gender: "female"},
            {name: "Dicle", meaning: "Tigris river", gender: "female"},
            {name: "Aldar", meaning: "The one who hold the flag, one another meaning comes from the Alder Tree", gender: "male"},
            {name: "Azadî", meaning: "Freedom", gender: "female"},
            {name: "Avêsta", meaning: "The Avesta is the primary collection of religious texts of Zoroastrianism", gender: "female"},
            {name: "Arjîn", meaning: "The fire of life", gender: "female"},
            {name: "Adar", meaning: "March", gender: "female"},
            {name: "Nisrîn", meaning: "Wild rose", gender: "female"},
            {name: "Şerîn", meaning: "Sweet", gender: "female"},
            {name: "Jîn", meaning: "Life", gender: "female"},
            {name: "Havîn", meaning: "Summer", gender: "female"},
            {name: "Eylem", meaning: "Action, has the same meaning in Turkish", gender: "female"},
            {name: "Rengîn", meaning: "Colorful", gender: "female"},
            {name: "Dara", meaning: "Wealthy", gender: "male"},
            {name: "Nûcan", meaning: "The new soul", gender: "female"},
            {name: "Ciwana", meaning: "Young, pretty", gender: "female"},
            {name: "Cotkar", meaning: "Farmer", gender: "male"},
            {name: "Hemrîn", meaning: "A mountain range name in Başur or Southern Kurdistan", gender: "female"},
            {name: "Gulşîn", meaning: "blooming flower", gender: "female"},
            {name: "Sîlva", meaning: "Pal", gender: "female"},
            {name: "Gelhat", meaning: "Pal", gender: "male"},
            {name: "Demhat", meaning: "Pal", gender: "male"},
            {name: "Zaniyar", meaning: "Pal", gender: "male"},
            {name: "Kawa", meaning: "Pal", gender: "male"},
            {name: "Zînda", meaning: "Pal", gender: "female"},
            {name: "Rêwan", meaning: "Pal", gender: "male"},
            {name: "Cansoz", meaning: "Pal", gender: "female"},
            {name: "Sozdar", meaning: "Pal", gender: "both"},
            {name: "Soz", meaning: "Pal", gender: "female"},
            {name: "Dilgeş", meaning: "Pal", gender: "male"},
            {name: "Tevgerîn", meaning: "Pal", gender: "female"},
            {name: "Hêlîm", meaning: "Pal", gender: "female"},
            {name: "Ruza", meaning: "Pal", gender: "female"},
            {name: "Ezda", meaning: "Pal", gender: "female"},
            {name: "Zinarîn", meaning: "Pal", gender: "female"},
            {name: "Zîn", meaning: "Pal", gender: "female"},
            {name: "Zevîn", meaning: "Pal", gender: "female"},
            {name: "Zîlan", meaning: "Pal", gender: "female"},
            {name: "Zelal", meaning: "Pal", gender: "female"},
            {name: "Tolvîn", meaning: "Pal", gender: "female"},
            {name: "Siyajîn", meaning: "Pal", gender: "female"},
            {name: "Şevîn", meaning: "Pal", gender: "female"},
            {name: "Sema", meaning: "Pal", gender: "female"},
            {name: "Sarya", meaning: "Pal", gender: "female"},
            {name: "Sekîna", meaning: "Pal", gender: "female"},
            {name: "Nûjiyan", meaning: "Pal", gender: "female"},
            {name: "Nîrvana", meaning: "Pal", gender: "female"},
            {name: "Mîdya", meaning: "Pal", gender: "female"},
            {name: "Koçerîn", meaning: "Pal", gender: "female"},
            {name: "Hêvî", meaning: "Pal", gender: "female"},
            {name: "Hebûn", meaning: "Pal", gender: "female"},
            {name: "Bûhar", meaning: "Pal", gender: "female"},
            {name: "Evrîm", meaning: "Pal", gender: "female"},
            {name: "Evîn", meaning: "Pal", gender: "female"},
            {name: "Dîrok", meaning: "Pal", gender: "female"},
            {name: "Dîlan", meaning: "Pal", gender: "female"},
            {name: "Diljîn", meaning: "Pal", gender: "female"},
            {name: "Derya", meaning: "Pal", gender: "female"},
            {name: "Darşîn", meaning: "Pal", gender: "female"},
            {name: "Canyar", meaning: "Pal", gender: "female"},
            {name: "Biharîn", meaning: "Pal", gender: "female"},
            {name: "Binevş", meaning: "Pal", gender: "female"},
            {name: "Bermal", meaning: "Pal", gender: "female"},
            {name: "Axîn", meaning: "Pal", gender: "female"},
            {name: "Awaz", meaning: "Pal", gender: "female"},
            {name: "Ararat", meaning: "Pal", gender: "female"},
            {name: "Agirîn", meaning: "Pal", gender: "female"},
            {name: "Dilovan", meaning: "Pal", gender: "male"},
            {name: "Zozan", meaning: "Pal", gender: "female"},
            {name: "Zêrîn", meaning: "Pal", gender: "female"},
            {name: "Penaber", meaning: "Pal", gender: "male"},
            {name: "Stêrk", meaning: "Pal", gender: "female"},
            {name: "Siyadem", meaning: "Pal", gender: "female"},
            {name: "Rojen", meaning: "Pal", gender: "female"},
            {name: "Perwîn", meaning: "Pal", gender: "female"},
            {name: "Nûjîn", meaning: "Pal", gender: "female"},
            {name: "Hîvda", meaning: "Pal", gender: "female"},
            {name: "Gulan", meaning: "Pal", gender: "female"},
            {name: "Çekjîn", meaning: "Pal", gender: "female"},
            {name: "Asmîn", meaning: "Pal", gender: "female"},
            {name: "Ahîn", meaning: "Pal", gender: "female"},
            {name: "Xezal", meaning: "Pal", gender: "female"},
            {name: "Şerda", meaning: "Pal", gender: "female"},
            {name: "Şaristan", meaning: "Pal", gender: "female"},
            {name: "Rojevîn", meaning: "Pal", gender: "female"},
            {name: "Fîdan", meaning: "Pal", gender: "female"},
            {name: "Dilsoz", meaning: "Pal", gender: "female"},
            {name: "Destîna", meaning: "Pal", gender: "female"},
            {name: "Rozerîn", meaning: "Pal", gender: "female"},
            {name: "Rehşan", meaning: "Pal", gender: "female"},
            {name: "Cudî", meaning: "Pal", gender: "male"},
            {name: "Narîn", meaning: "Pal", gender: "female"},
            {name: "Lêgerîn", meaning: "Pal", gender: "female"},
            {name: "Lîlav", meaning: "Pal", gender: "female"},
            {name: "Doza", meaning: "Pal", gender: "female"},
            {name: "Rojiyan", meaning: "Pal", gender: "female"},
            {name: "Bişeng", meaning: "Pal", gender: "female"},
            {name: "Barîn", meaning: "Pal", gender: "female"},
            {name: "Rûheyv", meaning: "Pal", gender: "female"},
            {name: "Nûpelda", meaning: "Pal", gender: "female"},
            {name: "Nêrgiz", meaning: "Pal", gender: "female"},
            {name: "Norşîn", meaning: "Pal", gender: "female"},
            {name: "Emgîhan", meaning: "Pal", gender: "female"},
            {name: "Hêzil", meaning: "Pal", gender: "both"},
            {name: "Aras", meaning: "Pal", gender: "male"},
            {name: "Emgîhan", meaning: "Pal", gender: "female"},
            {name: "Lorîn", meaning: "Pal", gender: "female"},
            {name: "Tîrêj", meaning: "Pal", gender: "male"},
            {name: "Alan", meaning: "Pal", gender: "male"},
            {name: "Canda", meaning: "Pal", gender: "female"},
            {name: "Heqî", meaning: "Pal", gender: "male"},
            {name: "Şerzan", meaning: "Pal", gender: "male"},
            {name: "Hêvîdar", meaning: "Pal", gender: "female"},
            {name: "Leşker", meaning: "Pal", gender: "male"},
            {name: "Hîra", meaning: "Pal", gender: "female"},
            {name: "Hîwa", meaning: "Pal", gender: "male"},
            {name: "Ruşan", meaning: "Pal", gender: "male"},
            {name: "Canfeda", meaning: "Pal", gender: "male"},
            {name: "Rêdûr", meaning: "Pal", gender: "male"},
            {name: "Sîdar", meaning: "Pal", gender: "male"},
            {name: "Şêrhat", meaning: "Pal", gender: "male"},
            {name: "Hazir", meaning: "Pal", gender: "male"},
            {name: "Kamîran", meaning: "Pal", gender: "male"},
            {name: "Baran", meaning: "Pal", gender: "male"},
            {name: "Bakur", meaning: "Pal", gender: "male"},
            {name: "Rêzan", meaning: "Pal", gender: "male"},
            {name: "Şêrwan", meaning: "Pal", gender: "male"},
            {name: "Ronya", meaning: "Pal", gender: "female"},
            {name: "Bêdeng", meaning: "Pal", gender: "male"},
            {name: "Hazir", meaning: "Pal", gender: "male"},
            {name: "Arşîn", meaning: "Pal", gender: "female"},
            {name: "Şerko", meaning: "Pal", gender: "male"},
            {name: "Aram", meaning: "Pal", gender: "male"},
            {name: "Comerd", meaning: "Pal", gender: "male"},
            {name: "Rojger", meaning: "Pal", gender: "male"},
            {name: "Avînar", meaning: "Pal", gender: "female"},
            {name: "Bendewar", meaning: "Pal", gender: "male"},
            {name: "Çem", meaning: "Pal", gender: "female"},
            {name: "Bager", meaning: "Pal", gender: "male"},
            {name: "Asrîn", meaning: "Pal", gender: "female"},
            {name: "Rojhat", meaning: "Pal", gender: "male"},
            {name: "Rêvana", meaning: "Pal", gender: "female"},
            {name: "Navdar", meaning: "Pal", gender: "male"},
            {name: "Polat", meaning: "Pal", gender: "male"},
            {name: "Zana", meaning: "Pal", gender: "male"},
            {name: "Masîro", meaning: "Pal", gender: "male"},
            {name: "Mîtan", meaning: "Pal", gender: "male"},
            {name: "Memo", meaning: "Pal", gender: "male"},
            {name: "Salar", meaning: "Pal", gender: "male"},
            {name: "Dilbirîn", meaning: "Pal", gender: "both"},
            {name: "Beyar", meaning: "Pal", gender: "male"},
            {name: "Seydo", meaning: "Pal", gender: "male"},
            {name: "Xweşnav", meaning: "Pal", gender: "male"},
            {name: "Baz", meaning: "Pal", gender: "male"},
            {name: "Goran", meaning: "Pal", gender: "male"},
            {name: "Dilyar", meaning: "Pal", gender: "male"},
            {name: "Elefteriya", meaning: "Pal", gender: "female"},
            {name: "Serxwebûn", meaning: "Pal", gender: "male"},
            {name: "Koçber", meaning: "Pal", gender: "male"},
            {name: "Reşo", meaning: "Pal", gender: "male"},
            {name: "Kanîwar", meaning: "Pal", gender: "male"},
            {name: "Zîr", meaning: "Pal", gender: "male"},
            {name: "Ayaz", meaning: "Pal", gender: "male"},
            {name: "Sara", meaning: "Pal", gender: "female"},
            {name: "Dîno", meaning: "Pal", gender: "male"},
            {name: "Şemdîn", meaning: "Pal", gender: "male"},
            {name: "Simko", meaning: "Pal", gender: "male"},
            {name: "Şevîn", meaning: "Pal", gender: "female"},
            {name: "Soro", meaning: "Pal", gender: "male"},
            {name: "Gurê Reş", meaning: "Pal", gender: "male"},
            {name: "Cîger", meaning: "Pal", gender: "male"},
            {name: "Rohat", meaning: "Pal", gender: "male"},
            {name: "Sêvdar", meaning: "Pal", gender: "male"},
            {name: "Dilcan", meaning: "Pal", gender: "male"},
            {name: "Çiyazan", meaning: "Pal", gender: "male"},
            {name: "Siyamend", meaning: "Pal", gender: "male"},
            {name: "Birîndar", meaning: "Pal", gender: "male"},
            {name: "Serkeft", meaning: "Pal", gender: "male"},
            {name: "Warhat", meaning: "Pal", gender: "male"},
            {name: "Dewran", meaning: "Pal", gender: "male"},
    ]

export const last_names =
    [
        {name: "Hesekê", meaning: "It is a city name located in Rojava or Western Kurdistan", gender: "both"},
        {name: "Şikakî", meaning: "A Kurdish tribe name", gender: "both"},
        {name: "Roj", meaning: "Pal", gender: "both"},
        {name: "Botan", meaning: "Pal", gender: "both"},
        {name: "Dêrsim", meaning: "Pal", gender: "both"},
        {name: "Munzur", meaning: "Pal", gender: "both"},
        {name: "Serhed", meaning: "Pal", gender: "both"},
        {name: "Sêrt", meaning: "Pal", gender: "both"},
        {name: "Agirî", meaning: "Pal", gender: "both"},
        {name: "Agir", meaning: "Pal", gender: "both"},
        {name: "Qamişlo", meaning: "Pal", gender: "both"},
        {name: "Goyî", meaning: "Pal", gender: "both"},
        {name: "Lîce", meaning: "Pal", gender: "both"},
        {name: "Serdem", meaning: "Pal", gender: "both"},
        {name: "Bêrîvan", meaning: "Pal", gender: "female"},
        {name: "Şêrewa", meaning: "Pal", gender: "both"},
        {name: "Azadî", meaning: "Pal", gender: "both"},
        {name: "Ronî", meaning: "Pal", gender: "both"},
        {name: "Amed", meaning: "Pal", gender: "both"},
        {name: "Cesur", meaning: "Pal", gender: "both"},
        {name: "Efrîn", meaning: "Pal", gender: "both"},
            {name: "Kobanê", meaning: "Pal", gender: "both"},
            {name: "Serdar", meaning: "Pal", gender: "both"},
            {name: "Newroz", meaning: "Pal", gender: "female"},
            {name: "Welat", meaning: "Pal", gender: "both"},
            {name: "Herekol", meaning: "Pal", gender: "male"},
            {name: "Canşêr", meaning: "Pal", gender: "male"},
            {name: "Siyabend", meaning: "Pal", gender: "male"},
            {name: "Partîzan", meaning: "Pal", gender: "male"},
            {name: "Bahoz", meaning: "Pal", gender: "male"},
            {name: "Şirnex", meaning: "Pal", gender: "both"},
            {name: "Tekoşer", meaning: "Pal", gender: "both"},
            {name: "Berxwedan", meaning: "Pal", gender: "both"},
            {name: "Sîpan", meaning: "Pal", gender: "male"},
            {name: "Herdem", meaning: "Pal", gender: "both"},
            {name: "Rodî", meaning: "Pal", gender: "female"},
            {name: "Cudî", meaning: "Pal", gender: "both"},
            {name: "Cigerxwîn", meaning: "Pal", gender: "both"},
            {name: "Farqîn", meaning: "Pal", gender: "both"},
            {name: "Pirsus", meaning: "Pal", gender: "both"},
            {name: "Gerzan", meaning: "Pal", gender: "both"},
            {name: "Koçer", meaning: "Pal", gender: "both"},
            {name: "Xwînrêj", meaning: "Pal", gender: "both"},
            {name: "Tolhildan", meaning: "Pal", gender: "both"},
            {name: "Karker", meaning: "Pal", gender: "both"},
            {name: "Rûşîn", meaning: "Pal", gender: "female"},
            {name: "Zagros", meaning: "Pal", gender: "both"},
            {name: "Arî", meaning: "Pal", gender: "male"},
            {name: "Çiya", meaning: "Pal", gender: "female"},
            {name: "Bagok", meaning: "Pal", gender: "both"},
            {name: "Rojhilat", meaning: "Pal", gender: "both"},
            {name: "Erdal", meaning: "Pal", gender: "both"},
            {name: "Bawer", meaning: "Pal", gender: "both"},
            {name: "Sefqan", meaning: "Pal", gender: "male"},
            {name: "Brûsk", meaning: "Pal", gender: "male"},
            {name: "Serhildan", meaning: "Pal", gender: "both"},
            {name: "Elend", meaning: "Pal", gender: "female"},
            {name: "Zerdeşt", meaning: "Pal", gender: "both"},
            {name: "Colemêrg", meaning: "Pal", gender: "both"},
            {name: "Dilşad", meaning: "Pal", gender: "female"},
            {name: "Nuda", meaning: "Pal", gender: "female"},
            {name: "Bêrîtan", meaning: "Pal", gender: "female"},
            {name: "Qendîl", meaning: "Pal", gender: "both"},
            {name: "Dêrik", meaning: "Pal", gender: "both"},
            {name: "Kurdo", meaning: "Pal", gender: "male"},
            {name: "Avareş", meaning: "Pal", gender: "female"},
            {name: "Piling", meaning: "Pal", gender: "male"},
            {name: "Şevger", meaning: "Pal", gender: "both"},
            {name: "Rêdar", meaning: "Pal", gender: "both"},
            {name: "Fedekar", meaning: "Pal", gender: "both"},
            {name: "Azad", meaning: "Pal", gender: "both"},
            {name: "Can", meaning: "Pal", gender: "both"},
            {name: "Gabar", meaning: "Pal", gender: "both"},
            {name: "Gever", meaning: "Pal", gender: "both"},
            {name: "Çarçela", meaning: "Pal", gender: "female"},
            {name: "Amanos", meaning: "Pal", gender: "both"},
            {name: "Gever", meaning: "Pal", gender: "both"},
            {name: "Rojava", meaning: "Pal", gender: "both"},
            {name: "Firat", meaning: "Pal", gender: "both"},
            {name: "Havîn", meaning: "Pal", gender: "female"},
            {name: "Nûcan", meaning: "Pal", gender: "female"},
            {name: "Ciwana", meaning: "Pal", gender: "female"},
            {name: "Dara", meaning: "Pal", gender: "female"},
            {name: "Cotkar", meaning: "Pal", gender: "both"},
            {name: "Serêkaniyê", meaning: "Pal", gender: "both"},
            {name: "Amûdê", meaning: "Pal", gender: "both"},
            {name: "Çilaxa", meaning: "Pal", gender: "both"},
            {name: "Hewlêr", meaning: "Pal", gender: "both"},
            {name: "Hemrîn", meaning: "Pal", gender: "female"},
            {name: "Mêrdîn", meaning: "Pal", gender: "both"},
            {name: "Batman", meaning: "Pal", gender: "both"},
            {name: "Şoreşger", meaning: "Pal", gender: "both"},
            {name: "Demhat", meaning: "Pal", gender: "both"},
            {name: "Zaniyar", meaning: "Pal", gender: "both"},
            {name: "Kawa", meaning: "Pal", gender: "both"},
            {name: "Dilgeş", meaning: "Pal", gender: "male"},
            {name: "Soz", meaning: "Pal", gender: "female"},
            {name: "Sozdar", meaning: "Pal", gender: "both"},
            {name: "Ararat", meaning: "Pal", gender: "both"},
            {name: "Dilbarîn", meaning: "Pal", gender: "female"},
            {name: "Jîn", meaning: "Pal", gender: "female"},
            {name: "Xabur", meaning: "Pal", gender: "both"},
            {name: "Sosin", meaning: "Pal", gender: "female"},
            {name: "Avaşîn", meaning: "Pal", gender: "both"},
            {name: "Dilovan", meaning: "Pal", gender: "both"},
            {name: "Zêrîn", meaning: "Pal", gender: "female"},
            {name: "Penaber", meaning: "Pal", gender: "both"},
            {name: "Stêrk", meaning: "Pal", gender: "female"},
            {name: "Hekkarî", meaning: "Pal", gender: "both"},
            {name: "Siyadem", meaning: "Pal", gender: "both"},
            {name: "Nûjîn", meaning: "Pal", gender: "female"},
            {name: "Gulan", meaning: "Pal", gender: "female"},
            {name: "Çekjîn", meaning: "Pal", gender: "female"},
            {name: "Fîdan", meaning: "Pal", gender: "female"},
            {name: "Nûhilat", meaning: "Pal", gender: "female"},
            {name: "Dilsoz", meaning: "Pal", gender: "female"},
            {name: "Rojevîn", meaning: "Pal", gender: "female"},
            {name: "Pîroz", meaning: "Pal", gender: "female"},
            {name: "Aras", meaning: "Pal", gender: "both"},
            {name: "Şêran", meaning: "Pal", gender: "both"},
            {name: "Serbilind", meaning: "Pal", gender: "both"},
            {name: "Tîrêj", meaning: "Pal", gender: "both"},
            {name: "Çîçek", meaning: "Pal", gender: "female"},
            {name: "Girkêlegê", meaning: "Pal", gender: "both"},
            {name: "Kurdistan", meaning: "Pal", gender: "both"},
            {name: "Nisêbîn", meaning: "Pal", gender: "both"},
            {name: "Qereçox", meaning: "Pal", gender: "both"},
            {name: "Pîr", meaning: "Pal", gender: "male"},
            {name: "Rûmet", meaning: "Pal", gender: "both"},
            {name: "Bêkes", meaning: "Pal", gender: "both"},
            {name: "Bendewar", meaning: "Pal", gender: "both"},
            {name: "Wan", meaning: "Pal", gender: "both"},
            {name: "Polat", meaning: "Pal", gender: "both"},
            {name: "Kaniya Kurda", meaning: "Pal", gender: "both"},
            {name: "Dirbesiyê", meaning: "Pal", gender: "both"},
            {name: "Baz", meaning: "Pal", gender: "both"},
            {name: "Elefteriya", meaning: "Pal", gender: "female"},
            {name: "Koçber", meaning: "Pal", gender: "both"},
            {name: "Çira", meaning: "Pal", gender: "both"},
            {name: "Reş", meaning: "Pal", gender: "male"},
            {name: "Şemdîn", meaning: "Pal", gender: "male"},
            {name: "Simko", meaning: "Pal", gender: "both"},
            {name: "Bêlwêran", meaning: "Pal", gender: "both"},
    ]