export const first_names =
    [
        {name: "Şiyar", meaning: "Watchful person, vigilant", gender: "male"},
        {name: "Cemal", meaning: "Beauty, this name has an Arabic origin", gender: "male"},
        {name: "Hogir", meaning: "Pal", gender: "male"},
        {name: "Rênas", meaning: "The one who knows the road very well", gender: "male"},
        {name: "Roj", meaning: "Sun, day in some dialects", gender: "both"},
        {name: "Dêrsim", meaning: "A Kurdish city in Bakur or Northern Kurdistan", gender: "male"},
        {name: "Munzur", meaning: "A river name in Bakur or Northern Kurdistan", gender: "male"},
        {name: "Botan", meaning: "A historical region name in Bakur or Northern Kurdistan", gender: "male"},
        {name: "Mezlum", meaning: "Oppressed", gender: "male"},
        {name: "Serhed", meaning: "The area to the north of the border, Hed means the border that divided Rojava and Bakur so Serhed means Bakur", gender: "male"},
        {name: "Serbest", meaning: "Free", gender: "male"},
        {name: "Tekoşer", meaning: "Struggler", gender: "male"},
        {name: "Agirî", meaning: "A mountain name in Bakur or Northern Kurdistan", gender: "male"},
        {name: "Agir", meaning: "Fire", gender: "male"},
        {name: "Dijwar", meaning: "Strong, like saying this chemical material is so strong", gender: "male"},
        {name: "Gelî", meaning: "Waterfall, national", gender: "male"},
        {name: "Şerzan", meaning: "Knows how to fight very well", gender: "male"},
        {name: "Xebat", meaning: "Work, the good meaning of it", gender: "male"},
        {name: "Serdem", meaning: "Due date, he knows well about the age we live in", gender: "male"},
        {name: "Rûken", meaning: "The one with smiley face", gender: "female"},
        {name: "Bêrîvan", meaning: "The woman who milks the cattle", gender: "female"},
        {name: "Xemgîn", meaning: "Sad", gender: "male"},
        {name: "Destan", meaning: "Epic", gender: "female"},
            {name: "Ciwan", meaning: "Young, beautiful", gender: "male"},
            {name: "Amed", meaning: "A Kurdish city in Bakur or Northern Kurdistan, also the capital of the big Kurdistan", gender: "male"},
            {name: "Şervan", meaning: "Fighter", gender: "male"},
            {name: "Çîçek", meaning: "Rose", gender: "female"},
            {name: "Êrîş", meaning: "Attack", gender: "male"},
            {name: "Cesur", meaning: "Bold", gender: "male"},
            {name: "Kerwan", meaning: "Convoy", gender: "male"},
            {name: "Ferhad", meaning: "True lover", gender: "male"},
            {name: "Diyar", meaning: "Country, it has an islamic origin and multiple meanings in Arabic and Urdu", gender: "male"},
            {name: "Çiya", meaning: "Mountain", gender: "male"},
            {name: "Serdar", meaning: "The one in the top, when it literally means the one on the tree", gender: "male"},
            {name: "Şevreş", meaning: "Dark night", gender: "both"},
            {name: "Hozan", meaning: "Singer", gender: "male"},
            {name: "Rojda", meaning: "Day-giver, Sun-giver", gender: "female"},
            {name: "Rojîn", meaning: "The lively face", gender: "female"},
            {name: "Ronî", meaning: "Light", gender: "male"},
            {name: "Şîmal", meaning: "A Kind of tree, also there is a village in Azerbaijan with this name", gender: "female"},
            {name: "Newroz", meaning: "The new day, and it is also the name of the national Kurdish day, the same day that different Iranian people celebrate it", gender: "female"},
            {name: "Lewend", meaning: "Graceful", gender: "male"},
            {name: "Xelîl", meaning: "Lover, it means the same in Arabic as well", gender: "male"},
            {name: "Welat", meaning: "Homeland", gender: "male"},
            {name: "Elîf", meaning: "A, The first letter in different alphabets", gender: "female"},
            {name: "Herekol", meaning: "A mountain name in Bakur or Northern Kurdistan", gender: "male"},
            {name: "Canşêr", meaning: "The tiger soul", gender: "male"},
            {name: "Jînda", meaning: "The one who gave the life", gender: "female"},
            {name: "Rêber", meaning: "The leader", gender: "male"},
            {name: "Siyabend", meaning: "Slender as a thread shadow, it is a the male hero name in the traditional Kurdish love story (Siyabend û Xecê)", gender: "male"},
            {name: "Partîzan", meaning: "Resistant", gender: "male"},
            {name: "Şoreş", meaning: "Revolution", gender: "male"},
            {name: "Argeş", meaning: "Blazing fire", gender: "male"},
            {name: "Bahoz", meaning: "Storm", gender: "male"},
            {name: "Berxwedan", meaning: "Resistance", gender: "male"},
            {name: "Egîd", meaning: "Brave, historically the bravest man in the village/neighbourhood was named Egîd", gender: "male"},
            {name: "Sîpan", meaning: "A mountain name in Bakur or Northern Kurdistan", gender: "male"},
            {name: "Herdem", meaning: "Everytime, the one who is here every time", gender: "male"},
            {name: "Rodî", meaning: "Literally it means the face that saw the sun, or brightness", gender: "male"},
            {name: "Rûbar", meaning: "Opposite or river", gender: "male"},
            {name: "Şivan", meaning: "Shepherd", gender: "male"},
            {name: "Cigerxwîn", meaning: "The bloody liver, the name of a famous Kurdish national poet", gender: "male"},
            {name: "Dilêr", meaning: "Hero, the one that is brave in wars or dangerous situations", gender: "male"},
            {name: "Dilxwaz", meaning: "He has willing, or literally his heart wants to", gender: "male"},
            {name: "Koçer", meaning: "Kurdish Bedouin, the usual nickname of Kurds in the bedouin tribes (mostly historically)", gender: "male"},
            {name: "Tolhildan", meaning: "Revenge", gender: "male"},
            {name: "Karker", meaning: "Worker", gender: "male"},
            {name: "Rûşîn", meaning: "The sad face, solace face", gender: "female"},
            {name: "Arî", meaning: "Aryan", gender: "male"},
            {name: "Zagros", meaning: "A long mountain range name in Rojhilat or Eastern Kurdistan", gender: "male"},
            {name: "Armanc", meaning: "Purpose, Aim", gender: "male"},
            {name: "Berfîn", meaning: "Snow", gender: "female"},
            {name: "Erdal", meaning: "A young person, has the same meaning in Turkish", gender: "male"},
            {name: "Rizgar", meaning: "Liberal", gender: "male"},
            {name: "Rojbîn", meaning: "The one who will bring the sun/day", gender: "female"},
            {name: "Bawer", meaning: "Convinced", gender: "male"},
            {name: "Sefqan", meaning: "The bloody head", gender: "male"},
            {name: "Brûsk", meaning: "Hailstones", gender: "male"},
            {name: "Elend", meaning: "The first ray of the sun in the morning", gender: "male"},
            {name: "Zerdeşt", meaning: "Zoroaster", gender: "male"},
            {name: "Dilşad", meaning: "Happy heart", gender: "male"},
            {name: "Lezgîn", meaning: "Hasty", gender: "male"},
            {name: "Nuda", meaning: "New gift, the god has given her again", gender: "female"},
            {name: "Bêrîtan", meaning: "A Kurdish tribe name", gender: "female"},
            {name: "Sînan", meaning: "Spearhead", gender: "male"},
            {name: "Tekoşîn", meaning: "Struggle", gender: "female"},
            {name: "Xwînda", meaning: "Blood giver", gender: "female"},
            {name: "Qendîl", meaning: "A mountain name in Başur or Southern Kurdistan", gender: "male"},
            {name: "Çiyager", meaning: "The one who walk through mountains", gender: "male"},
            {name: "Amara", meaning: "Eternal beauty", gender: "female"},
            {name: "Devrim", meaning: "Revolution, and has the same meaning in Turkish", gender: "male"},
            {name: "Kendal", meaning: "Slope", gender: "male"},
            {name: "Rûstem", meaning: "The name of the Iranian mythic hero Rostam", gender: "male"},
            {name: "Viyan", meaning: "Intention or wish", gender: "female"},
            {name: "Yaşar", meaning: "Ease", gender: "male"},
            {name: "Piling", meaning: "Panther", gender: "male"},
            {name: "Şevger", meaning: "The one who walks in the night", gender: "male"},
            {name: "Çeleng", meaning: "Elegant, gracious, pretty", gender: "male"},
            {name: "Fedekar", meaning: "Sacrificing person", gender: "male"},
            {name: "Azad", meaning: "Free", gender: "male"},
            {name: "Can", meaning: "Soul, young, pretty", gender: "male"},
            {name: "Arîn", meaning: "The continues ache", gender: "female"},
            {name: "Gabar", meaning: "A mountain name in Bakur or Northern Kurdistan", gender: "male"},
            {name: "Canpolat", meaning: "The steely soul", gender: "male"},
            {name: "Çarçela", meaning: "A mountain name in Bakur or Northern Kurdistan", gender: "female"},
            {name: "Çekdar", meaning: "Armed", gender: "male"},
            {name: "Delîla", meaning: "Guide", gender: "female"},
            {name: "Dilşêr", meaning: "The tiger heart", gender: "male"},
            {name: "Hawar", meaning: "Cry for help", gender: "male"},
            {name: "Hewlêr", meaning: "A Kurdish city in Başur or Southern Kurdistan, Erbil", gender: "female"},
            {name: "Qehreman", meaning: "Hero", gender: "male"},
            {name: "Firat", meaning: "Euphrates river", gender: "male"},
            {name: "Tîmaf", meaning: "Thirst for his rights", gender: "male"},
            {name: "Xemlîn", meaning: "adornment", gender: "female"},
            {name: "Warşîn", meaning: "The green homeland", gender: "female"},
            {name: "Jiyan", meaning: "Life", gender: "female"},
            {name: "Vejîn", meaning: "Revival", gender: "female"},
            {name: "Sorxwîn", meaning: "Red blood", gender: "female"},
            {name: "Şîlan", meaning: "Wild rose", gender: "female"},
            {name: "Ronahî", meaning: "Light", gender: "female"},
            {name: "Peyman", meaning: "Agreement", gender: "female"},
            {name: "Raperîn", meaning: "Uprising", gender: "female"},
            {name: "Nejbîr", meaning: "Diligent", gender: "female"},
            {name: "Jiyanda", meaning: "The one who gave the life", gender: "female"},
            {name: "Hêlîn", meaning: "The nest", gender: "female"},
            {name: "Hêvîdar", meaning: "The wisher", gender: "female"},
            {name: "Gulnaz", meaning: "Tender rose", gender: "female"},
            {name: "Gulîstan", meaning: "A house of flowers", gender: "female"},
            {name: "Dîdar", meaning: "Jovial, cheery", gender: "female"},
            {name: "Dicle", meaning: "Tigris river", gender: "female"},
            {name: "Aldar", meaning: "The one who hold the flag, one another meaning comes from the Alder Tree", gender: "male"},
            {name: "Azadî", meaning: "Freedom", gender: "female"},
            {name: "Avêsta", meaning: "The Avesta is the primary collection of religious texts of Zoroastrianism", gender: "female"},
            {name: "Arjîn", meaning: "The fire of life", gender: "female"},
            {name: "Adar", meaning: "March", gender: "female"},
            {name: "Nisrîn", meaning: "Wild rose", gender: "female"},
            {name: "Şerîn", meaning: "Sweet", gender: "female"},
            {name: "Jîn", meaning: "Life", gender: "female"},
            {name: "Havîn", meaning: "Summer", gender: "female"},
            {name: "Eylem", meaning: "Action, has the same meaning in Turkish", gender: "female"},
            {name: "Rengîn", meaning: "Colorful", gender: "female"},
            {name: "Dara", meaning: "Wealthy", gender: "male"},
            {name: "Nûcan", meaning: "The new soul", gender: "female"},
            {name: "Ciwana", meaning: "Young, pretty", gender: "female"},
            {name: "Cotkar", meaning: "Farmer", gender: "male"},
            {name: "Hemrîn", meaning: "A mountain range name in Başur or Southern Kurdistan", gender: "female"},
            {name: "Gulşîn", meaning: "blooming flower", gender: "female"},
            {name: "Sîlva", meaning: "Has a Spanish origin and it means a tract of land covered by dense equatorial forest, especially in the Amazon basin.", gender: "female"},
            {name: "Gelhat", meaning: "The people has came, or people has awaken", gender: "male"},
            {name: "Demhat", meaning: "The time hase came, it is the appropriate time", gender: "male"},
            {name: "Zaniyar", meaning: "Informative", gender: "male"},
            {name: "Kawa", meaning: "An ancient kurdish mythical hero", gender: "male"},
            {name: "Zînda", meaning: "She gave the life", gender: "female"},
            {name: "Rêwan", meaning: "The road to Wan/Van city", gender: "male"},
            {name: "Cansoz", meaning: "He promises with his soul", gender: "female"},
            {name: "Sozdar", meaning: "A person of his word, promisor", gender: "both"},
            {name: "Soz", meaning: "Promise", gender: "female"},
            {name: "Dilgeş", meaning: "Shinning heart", gender: "male"},
            {name: "Tevgerîn", meaning: "Movement", gender: "female"},
            {name: "Hêlîm", meaning: "Patient, has the same meaning in Arabic", gender: "female"},
            {name: "Ruza", meaning: "Rose", gender: "female"},
            {name: "Ezda", meaning: "God", gender: "female"},
            {name: "Zinarîn", meaning: "The top of the mountain", gender: "female"},
            {name: "Zîn", meaning: "Equal, balanced and it is the name of the female name in an old Kurdish love story (Mem û Zîn)", gender: "female"},
            {name: "Zevîn", meaning: "Orchards", gender: "female"},
            {name: "Zîlan", meaning: "Wind, storm", gender: "female"},
            {name: "Zelal", meaning: "Pure", gender: "female"},
            {name: "Tolvîn", meaning: "The one in love with revenge", gender: "female"},
            {name: "Siyajîn", meaning: "The shadow of the life", gender: "female"},
            {name: "Şevîn", meaning: "The night", gender: "female"},
            {name: "Sema", meaning: "Omen, sky, heaven", gender: "female"},
            {name: "Sarya", meaning: "Name of a pious woman, it has an Islamic origin", gender: "female"},
            {name: "Sekîna", meaning: "Quiet, an old Islamic/Arabic name", gender: "female"},
            {name: "Nûjiyan", meaning: "The new life", gender: "female"},
            {name: "Nîrvana", meaning: "Place of great bliss", gender: "female"},
            {name: "Mîdya", meaning: "Mother of kurds, from Medes", gender: "female"},
            {name: "Koçerîn", meaning: "Kurdish Bedouin, the usual nickname of Kurds in the bedouin tribes (mostly historically), female name of Koçer", gender: "female"},
            {name: "Hêvî", meaning: "Hope", gender: "female"},
            {name: "Hebûn", meaning: "Existence", gender: "female"},
            {name: "Bûhar", meaning: "Spring", gender: "female"},
            {name: "Evrîm", meaning: "Development", gender: "female"},
            {name: "Evîn", meaning: "Love", gender: "female"},
            {name: "Dîrok", meaning: "History", gender: "female"},
            {name: "Dîlan", meaning: "Dance", gender: "female"},
            {name: "Diljîn", meaning: "The heart of the life", gender: "female"},
            {name: "Derya", meaning: "Sea", gender: "female"},
            {name: "Darşîn", meaning: "The green tree", gender: "female"},
            {name: "Canyar", meaning: "The soul lover", gender: "female"},
            {name: "Biharîn", meaning: "Spring", gender: "female"},
            {name: "Binevş", meaning: "Violet", gender: "female"},
            {name: "Bermal", meaning: "housewife", gender: "female"},
            {name: "Axîn", meaning: "The groan of pain", gender: "female"},
            {name: "Awaz", meaning: "Tone, music", gender: "female"},
            {name: "Ararat", meaning: "A mountain name in Bakur or Northern Kurdistan & Armenia", gender: "female"},
            {name: "Agirîn", meaning: "A mountain name in Bakur or Northern Kurdistan, its name is Agirî so Agirîn is the female name of it", gender: "female"},
            {name: "Dilovan", meaning: "Friendly, merciful", gender: "male"},
            {name: "Zozan", meaning: "Grassland rich area", gender: "female"},
            {name: "Zêrîn", meaning: "Golden", gender: "female"},
            {name: "Penaber", meaning: "Refugee", gender: "male"},
            {name: "Stêrk", meaning: "Star", gender: "female"},
            {name: "Siyadem", meaning: "The shadow of the age", gender: "female"},
            {name: "Rojen", meaning: "The one with a beautiful face", gender: "female"},
            {name: "Perwîn", meaning: "The Pleiades", gender: "female"},
            {name: "Nûjîn", meaning: "The new life", gender: "female"},
            {name: "Hîvda", meaning: "The moon giver", gender: "female"},
            {name: "Gulan", meaning: "May", gender: "female"},
            {name: "Çekjîn", meaning: "The armed life", gender: "female"},
            {name: "Asmîn", meaning: "Derived from asîman meaning sky, or a type of wildflower.", gender: "female"},
            {name: "Ahîn", meaning: "Groaning", gender: "female"},
            {name: "Xezal", meaning: "Deer, has the same meaning in Arabic", gender: "female"},
            {name: "Şerda", meaning: "The fight giver", gender: "female"},
            {name: "Şaristan", meaning: "Civilization", gender: "female"},
            {name: "Rojevîn", meaning: "The sun of the love, or the day of the love", gender: "female"},
            {name: "Fîdan", meaning: "Shrub, has the same meaning in Turkish", gender: "female"},
            {name: "Dilsoz", meaning: "Faithful", gender: "female"},
            {name: "Destîna", meaning: "Female name of epic", gender: "female"},
            {name: "Rozêrîn", meaning: "The one with the golden face", gender: "female"},
            {name: "Rehşan", meaning: "The one with nevus on her chin", gender: "female"},
            {name: "Cudî", meaning: "A mountain name in Bakur or Northern Kurdistan, In Islam it is where Noah's ark docked", gender: "male"},
            {name: "Narîn", meaning: "Delicate, fragile, slender", gender: "female"},
            {name: "Lêgerîn", meaning: "The female name of the person who search for something", gender: "female"},
            {name: "Lîlav", meaning: "Melted snow", gender: "female"},
            {name: "Doza", meaning: "The path", gender: "female"},
            {name: "Rojiyan", meaning: "The full-of-life face", gender: "female"},
            {name: "Bişeng", meaning: "The pretty, colorful", gender: "female"},
            {name: "Barîn", meaning: "Rain, it is raining", gender: "female"},
            {name: "Rûheyv", meaning: "The moon face", gender: "female"},
            {name: "Nûpelda", meaning: "That bloomed again", gender: "female"},
            {name: "Nêrgiz", meaning: "Narcissus", gender: "female"},
            {name: "Norşîn", meaning: "It means new village in Armenian and it is the name of a village in Bakur or Northern Kurdistan", gender: "female"},
            {name: "Emgîhan", meaning: "We have reached", gender: "female"},
            {name: "Hêzil", meaning: "Power", gender: "both"},
            {name: "Aras", meaning: "A river name in Bakur or Northern Kurdistan", gender: "male"},
            {name: "Lorîn", meaning: "Cradle-song", gender: "female"},
            {name: "Tîrêj", meaning: "Falling star", gender: "male"},
            {name: "Alan", meaning: "Flag bearer", gender: "male"},
            {name: "Canda", meaning: "The one who sacrificed her soul", gender: "female"},
            {name: "Heqî", meaning: "God/Truth", gender: "male"},
            {name: "Leşker", meaning: "Fighter", gender: "male"},
            {name: "Hîra", meaning: "Vast", gender: "female"},
            {name: "Hîwa", meaning: "Hope", gender: "male"},
            {name: "Ruşan", meaning: "The one with nevus on her face", gender: "male"},
            {name: "Canfeda", meaning: "The one who sacrificed her soul", gender: "male"},
            {name: "Rêdûr", meaning: "The one with the long road", gender: "male"},
            {name: "Sîdar", meaning: "Shade or canopy", gender: "male"},
            {name: "Şêrhat", meaning: "The tiger has came", gender: "male"},
            {name: "Hazir", meaning: "Ready", gender: "male"},
            {name: "Kamîran", meaning: "Prosperous, fortunate, it has a Persian origin", gender: "male"},
            {name: "Baran", meaning: "Rain", gender: "male"},
            {name: "Bakur", meaning: "North", gender: "male"},
            {name: "Rêzan", meaning: "The one who knows the road very well", gender: "male"},
            {name: "Şêrwan", meaning: "Roaring sea or shouting river", gender: "male"},
            {name: "Ronya", meaning: "The Light (before the sunrise)", gender: "female"},
            {name: "Bêdeng", meaning: "Silent", gender: "male"},
            {name: "Arşîn", meaning: "Warrior of god, has the same meaning in Persian", gender: "female"},
            {name: "Şêrko", meaning: "Refer to Asad Ad-Din Sherko, a Kurdish General of Zengid army and uncle of Saladin", gender: "male"},
            {name: "Aram", meaning: "Calm", gender: "male"},
            {name: "Comerd", meaning: "Generous", gender: "male"},
            {name: "Rojger", meaning: "The one who walk during the day", gender: "male"},
            {name: "Avînar", meaning: "The fire of love", gender: "female"},
            {name: "Bendewar", meaning: "The person who waits", gender: "male"},
            {name: "Çem", meaning: "River", gender: "female"},
            {name: "Bager", meaning: "The one who moves the wind", gender: "male"},
            {name: "Asrîn", meaning: "Tear or teardrop", gender: "female"},
            {name: "Rojhat", meaning: "The sun shines", gender: "male"},
            {name: "Rêvana", meaning: "The one who is professional in the road", gender: "female"},
            {name: "Navdar", meaning: "Famous", gender: "male"},
            {name: "Polat", meaning: "Steel", gender: "male"},
            {name: "Zana", meaning: "Wisdom, clever, smart or scientist", gender: "male"},
            {name: "Masîro", meaning: "Maseru", gender: "male"},
            {name: "Mîtan", meaning: "From Mitanni, an old state in Mesopotamia", gender: "male"},
            {name: "Memo", meaning: "From Mem, it is derived from Mohammad, but in the Kurdish history he is the hero of an old love story (Mem û Zîn)", gender: "male"},
            {name: "Salar", meaning: "Leader or chief", gender: "male"},
            {name: "Dilbirîn", meaning: "Broken heart", gender: "both"},
            {name: "Beyar", meaning: "Loam soil", gender: "male"},
            {name: "Seydo", meaning: "From Seyd, means sir and has the same meaning in Arabic", gender: "male"},
            {name: "Xweşnav", meaning: "Beautiful name", gender: "male"},
            {name: "Baz", meaning: "Kurdistan mountains falcon", gender: "male"},
            {name: "Goran", meaning: "Mountain, has origin from Avestan which is an old Indo-Iranian language", gender: "male"},
            {name: "Dilyar", meaning: "Heart lover", gender: "male"},
            {name: "Elefteriya", meaning: "From Greek name Eleftheria, and it means freedom", gender: "female"},
            {name: "Serxwebûn", meaning: "Independence", gender: "male"},
            {name: "Koçber", meaning: "Emigrant", gender: "male"},
            {name: "Reşo", meaning: "Black", gender: "male"},
            {name: "Kanîwar", meaning: "The region where there are too many springs", gender: "male"},
            {name: "Zîr", meaning: "Smart", gender: "male"},
            {name: "Ayaz", meaning: "Cold and still air, has the same meaning in Turkish", gender: "male"},
            {name: "Sara", meaning: "From Sarah; lady, princess, noblewoman", gender: "female"},
            {name: "Dîno", meaning: "Crazy", gender: "male"},
            {name: "Şemdîn", meaning: "A Kurdish old family name in Damascus", gender: "male"},
            {name: "Simko", meaning: "From Hebrew name Ishmael and it means God will hear", gender: "male"},
            {name: "Soro", meaning: "Red", gender: "male"},
            {name: "Gurê Reş", meaning: "Black wolf", gender: "male"},
            {name: "Cîger", meaning: "Brave, liver", gender: "male"},
            {name: "Rohat", meaning: "The day/sun has came", gender: "male"},
            {name: "Sêvdar", meaning: "Apples tree", gender: "male"},
            {name: "Dilcan", meaning: "The one with the young heart", gender: "male"},
            {name: "Çiyazan", meaning: "The one who knows the mountains very well", gender: "male"},
            {name: "Siyamend", meaning: "From Siyabend, Slender as a thread shadow, a figure from an old Kurdish love story (Siyabend û Xecê)", gender: "male"},
            {name: "Birîndar", meaning: "Wounded", gender: "male"},
            {name: "Serkeft", meaning: "Success", gender: "male"},
            {name: "Warhat", meaning: "The homeland is close", gender: "male"},
            {name: "Dewran", meaning: "Strength, could also be Devran", gender: "male"},
        {name: "Çîmen", meaning: "Meadow, grass, lawn", gender: "female"},
        {name: "Dîlok", meaning: "Love song", gender: "female"},
        {name: "Dilvîn", meaning: "Merciful", gender: "female"},
        {name: "Dîmen", meaning: "Sight, view", gender: "female"},
        {name: "Gulbarîn", meaning: "Good rose, it is raining roses", gender: "female"},
        {name: "Helez", meaning: "Dill", gender: "female"},
    ]

export const last_names =
    [
        {name: "Hesekê", meaning: "It is a city name located in Rojava or Western Kurdistan", gender: "both"},
        {name: "Şikakî", meaning: "A Kurdish tribe name", gender: "both"},
        {name: "Roj", meaning: "Sun/Day", gender: "both"},
        {name: "Botan", meaning: "A historical region name in Bakur or Northern Kurdistan", gender: "both"},
        {name: "Dêrsim", meaning: "It is a city name located in Bakur or Northern Kurdistan", gender: "both"},
        {name: "Munzur", meaning: "A river name in Bakur or Northern Kurdistan", gender: "both"},
        {name: "Serhed", meaning: "The area to the north of the border, Hed means the border that divided Rojava and Bakur so Serhed means Bakur", gender: "both"},
        {name: "Sêrt", meaning: "It is a city name located in Bakur or Northern Kurdistan", gender: "both"},
        {name: "Agirî", meaning: "A mountain name in Bakur or Northern Kurdistan", gender: "both"},
        {name: "Agir", meaning: "Fire", gender: "both"},
        {name: "Qamişlo", meaning: "It is a city name located in Rojava or Western Kurdistan", gender: "both"},
        {name: "Goyî", meaning: "A Kurdish tribe name", gender: "both"},
        {name: "Lîce", meaning: "It is a city name located in Bakur or Northern Kurdistan", gender: "both"},
        {name: "Serdem", meaning: "Due date, he knows well about the age we live in", gender: "both"},
        {name: "Bêrîvan", meaning: "The woman who milks the cattle", gender: "female"},
        {name: "Şêrewa", meaning: "It is a town name located in Rojava or Western Kurdistan", gender: "both"},
        {name: "Azadî", meaning: "Freedom", gender: "both"},
        {name: "Ronî", meaning: "Light", gender: "both"},
        {name: "Amed", meaning: "A Kurdish city in Bakur or Northern Kurdistan, also the capital of the big Kurdistan", gender: "both"},
        {name: "Cesur", meaning: "Bold", gender: "both"},
        {name: "Efrîn", meaning: "It is a city name located in Rojava or Western Kurdistan", gender: "both"},
            {name: "Kobanê", meaning: "It is a city name located in Rojava or Western Kurdistan", gender: "both"},
            {name: "Serdar", meaning: "The one in the top, when it literally means the one on the tree", gender: "both"},
            {name: "Newroz", meaning: "The new day, and it is also the name of the national Kurdish day, the same day that different Iranian people celebrate it", gender: "female"},
            {name: "Welat", meaning: "Homeland", gender: "both"},
            {name: "Herekol", meaning: "A mountain name in Bakur or Northern Kurdistan", gender: "male"},
            {name: "Canşêr", meaning: "The tiger soul", gender: "male"},
            {name: "Siyabend", meaning: "Slender as a thread shadow, it is a the male hero name in the traditional Kurdish love story (Siyabend û Xecê)", gender: "male"},
            {name: "Partîzan", meaning: "Resistant", gender: "male"},
            {name: "Bahoz", meaning: "Storm", gender: "male"},
            {name: "Şirnex", meaning: "It is a city name located in Bakur or Northern Kurdistan", gender: "both"},
            {name: "Tekoşer", meaning: "Struggler", gender: "both"},
            {name: "Berxwedan", meaning: "Resistance", gender: "both"},
            {name: "Sîpan", meaning: "A mountain name in Bakur or Northern Kurdistan", gender: "male"},
            {name: "Herdem", meaning: "Everytime, the one who is here every time", gender: "both"},
            {name: "Rodî", meaning: "Literally it means the face that saw the sun, or brightness", gender: "female"},
            {name: "Cudî", meaning: "A mountain name in Bakur or Northern Kurdistan, In Islam it is where Noah's ark docked", gender: "both"},
            {name: "Cigerxwîn", meaning: "The bloody liver, the name of a famous Kurdish national poet", gender: "both"},
            {name: "Farqîn", meaning: "It is a city name located in Bakur or Northern Kurdistan", gender: "both"},
            {name: "Pirsus", meaning: "It is a city name located in Bakur or Northern Kurdistan", gender: "both"},
            {name: "Garzan", meaning: "It is a city name located in Bakur or Northern Kurdistan", gender: "both"},
            {name: "Koçer", meaning: "Kurdish Bedouin, the usual nickname of Kurds in the bedouin tribes (mostly historically)", gender: "both"},
            {name: "Xwînrêj", meaning: "Who sheds blood", gender: "both"},
            {name: "Tolhildan", meaning: "Revenge", gender: "both"},
            {name: "Karker", meaning: "Worker", gender: "both"},
            {name: "Rûşîn", meaning: "The sad face, solace face", gender: "female"},
            {name: "Zagros", meaning: "A long mountain range name in Rojhilat or Eastern Kurdistan", gender: "both"},
            {name: "Arî", meaning: "Aryan", gender: "male"},
            {name: "Çiya", meaning: "Mountain", gender: "female"},
            {name: "Bagok", meaning: "A region in Bakur or Northern Kurdistan", gender: "both"},
            {name: "Rojhilat", meaning: "East", gender: "both"},
            {name: "Erdal", meaning: "A young person, has the same meaning in Turkish", gender: "both"},
            {name: "Bawer", meaning: "Convinced", gender: "both"},
            {name: "Sefqan", meaning: "The bloody head", gender: "male"},
            {name: "Brûsk", meaning: "Hailstones", gender: "male"},
            {name: "Serhildan", meaning: "Rebellion", gender: "both"},
            {name: "Elend", meaning: "The first ray of the sun in the morning", gender: "female"},
            {name: "Zerdeşt", meaning: "Zoroaster", gender: "both"},
            {name: "Colemêrg", meaning: "It is a city name located in Bakur or Northern Kurdistan", gender: "both"},
            {name: "Dilşad", meaning: "Happy heart", gender: "female"},
            {name: "Nuda", meaning: "New gift, the god has given her again", gender: "female"},
            {name: "Bêrîtan", meaning: "A Kurdish tribe name", gender: "female"},
            {name: "Qendîl", meaning: "A mountain name in Başur or Southern Kurdistan", gender: "both"},
            {name: "Dêrik", meaning: "It is a city name located in Rojava or Western Kurdistan", gender: "both"},
            {name: "Kurdo", meaning: "Kurdish", gender: "male"},
            {name: "Avareş", meaning: "Black water", gender: "female"},
            {name: "Piling", meaning: "Panther", gender: "male"},
            {name: "Şevger", meaning: "The one who walks in the night", gender: "both"},
            {name: "Rêdar", meaning: "The road full of trees", gender: "both"},
            {name: "Fedekar", meaning: "Sacrificing person", gender: "both"},
            {name: "Azad", meaning: "Free", gender: "both"},
            {name: "Can", meaning: "Soul, young, pretty", gender: "both"},
            {name: "Gabar", meaning: "A mountain name in Bakur or Northern Kurdistan", gender: "both"},
            {name: "Gever", meaning: "It is a city name located in Bakur or Northern Kurdistan", gender: "both"},
            {name: "Çarçela", meaning: "A mountain name in Bakur or Northern Kurdistan", gender: "female"},
            {name: "Amanos", meaning: "A mountain range in Bakur or Northern Kurdistan", gender: "both"},
            {name: "Gever", meaning: "It is a city name located in Bakur or Northern Kurdistan", gender: "both"},
            {name: "Rojava", meaning: "West", gender: "both"},
            {name: "Firat", meaning: "Euphrates river", gender: "both"},
            {name: "Havîn", meaning: "Summer", gender: "female"},
            {name: "Nûcan", meaning: "The new soul", gender: "female"},
            {name: "Ciwana", meaning: "Young, pretty", gender: "female"},
            {name: "Dara", meaning: "Wealthy", gender: "female"},
            {name: "Cotkar", meaning: "Farmer", gender: "both"},
            {name: "Serêkaniyê", meaning: "It is a city name located in Rojava or Western Kurdistan", gender: "both"},
            {name: "Amûdê", meaning: "It is a city name located in Rojava or Western Kurdistan", gender: "both"},
            {name: "Çilaxa", meaning: "It is a town name located in Rojava or Western Kurdistan", gender: "both"},
            {name: "Hewlêr", meaning: "A Kurdish city in Başur or Southern Kurdistan, Erbil", gender: "both"},
            {name: "Hemrîn", meaning: "A mountain range name in Başur or Southern Kurdistan", gender: "female"},
            {name: "Mêrdîn", meaning: "It is a city name located in Bakur or Northern Kurdistan", gender: "both"},
            {name: "Batman", meaning: "It is a city name located in Bakur or Northern Kurdistan", gender: "both"},
            {name: "Şoreşger", meaning: "Revolutionary", gender: "both"},
            {name: "Demhat", meaning: "The time hase came, it is the appropriate time", gender: "both"},
            {name: "Zaniyar", meaning: "Informative", gender: "both"},
            {name: "Kawa", meaning: "An ancient kurdish mythical hero", gender: "both"},
            {name: "Dilgeş", meaning: "Shinning heart", gender: "male"},
            {name: "Soz", meaning: "Promise", gender: "female"},
            {name: "Sozdar", meaning: "A person of his word, promisor", gender: "both"},
            {name: "Ararat", meaning: "A mountain name in Bakur or Northern Kurdistan & Armenia", gender: "both"},
            {name: "Dilbarîn", meaning: "Divided heart", gender: "female"},
            {name: "Jîn", meaning: "Life", gender: "female"},
            {name: "Xabur", meaning: "A river name in Rojava or Western Kurdistan", gender: "both"},
            {name: "Sosin", meaning: "Lily, tulip", gender: "female"},
            {name: "Avaşîn", meaning: "Blue water", gender: "both"},
            {name: "Dilovan", meaning: "Friendly, merciful", gender: "both"},
            {name: "Zêrîn", meaning: "Golden", gender: "female"},
            {name: "Penaber", meaning: "Refugee", gender: "both"},
            {name: "Stêrk", meaning: "Star", gender: "female"},
            {name: "Hekkarî", meaning: "It is a city name located in Bakur or Northern Kurdistan", gender: "both"},
            {name: "Siyadem", meaning: "The shadow of the age", gender: "both"},
            {name: "Nûjîn", meaning: "The new life", gender: "female"},
            {name: "Gulan", meaning: "May", gender: "female"},
            {name: "Çekjîn", meaning: "The armed life", gender: "female"},
            {name: "Fîdan", meaning: "Shrub, has the same meaning in Turkish", gender: "female"},
            {name: "Nûhilat", meaning: "Newly raised", gender: "female"},
            {name: "Dilsoz", meaning: "Faithful", gender: "female"},
            {name: "Rojevîn", meaning: "The sun of the love, or the day of the love", gender: "female"},
            {name: "Pîroz", meaning: "Sacred, holy", gender: "female"},
            {name: "Aras", meaning: "A river name in Bakur or Northern Kurdistan", gender: "both"},
            {name: "Şêran", meaning: "It is a town name located in Rojava or Western Kurdistan", gender: "both"},
            {name: "Serbilind", meaning: "Proud", gender: "both"},
            {name: "Tîrêj", meaning: "Falling star", gender: "both"},
            {name: "Çîçek", meaning: "Rose", gender: "female"},
            {name: "Girkêlegê", meaning: "It is a town name located in Rojava or Western Kurdistan", gender: "both"},
            {name: "Kurdistan", meaning: "The Kurdish homeland", gender: "both"},
            {name: "Nisêbîn", meaning: "It is a city name located in Bakur or Northern Kurdistan", gender: "both"},
            {name: "Qereçox", meaning: "A small mountain name in Rojava or Westren Kurdistan", gender: "both"},
            {name: "Pîr", meaning: "Old", gender: "male"},
            {name: "Rûmet", meaning: "Glory", gender: "both"},
            {name: "Bêkes", meaning: "Lonely", gender: "both"},
            {name: "Bendewar", meaning: "The person who waits", gender: "both"},
            {name: "Wan", meaning: "It is a city name located in Bakur or Northern Kurdistan", gender: "both"},
            {name: "Polat", meaning: "Steel", gender: "both"},
            {name: "Kaniya Kurda", meaning: "The Kurdish spring", gender: "both"},
            {name: "Dirbesiyê", meaning: "It is a town name located in Rojava or Western Kurdistan", gender: "both"},
            {name: "Baz", meaning: "Kurdistan mountains falcon", gender: "both"},
            {name: "Elefteriya", meaning: "From Greek name Eleftheria, and it means freedom", gender: "female"},
            {name: "Koçber", meaning: "Emigrant", gender: "both"},
            {name: "Çira", meaning: "Candle", gender: "both"},
            {name: "Reş", meaning: "Black", gender: "male"},
            {name: "Şemdîn", meaning: "A Kurdish old family name in Damascus", gender: "male"},
            {name: "Simko", meaning: "From Hebrew name Ishmael and it means God will hear", gender: "both"},
            {name: "Bêlwêran", meaning: "It is a village name located in Bakur or Northern Kurdistan", gender: "both"},
            {name: "Bedew", meaning: "Cool", gender: "male"},
        {name: "Berav", meaning: "Shore", gender: "male"},
        {name: "Bozan", meaning: "Auburn", gender: "male"},
        {name: "Desmal", meaning: "Handkerchief", gender: "female"},
        {name: "Evîndar", meaning: "In love", gender: "male"},
        {name: "Gelavêj", meaning: "From the Kurdish name for the constellation Sirius", gender: "both"},
        {name: "Gerdûn", meaning: "Universe, world", gender: "both"},
        {name: "Hêja", meaning: "Dear", gender: "both"},
        {name: "Gazî", meaning: "Appeal, call for help", gender: "both"},
        {name: "Genco", meaning: "From genc and it means treasure, and also it means young", gender: "both"},
        {name: "Gewrê", meaning: "Grey", gender: "female"},
        {name: "Gulbax", meaning: "Garden rose", gender: "female"},
    ]